<?php

return [
    'UA' => ['flag' => '🇺🇦', 'uk' => 'Україна', 'en' => 'Ukraine'],
    'PL' => ['flag' => '🇵🇱', 'uk' => 'Польща', 'en' => 'Poland'],
    'DE' => ['flag' => '🇩🇪', 'uk' => 'Німеччина', 'en' => 'Germany'],
    'FR' => ['flag' => '🇫🇷', 'uk' => 'Франція', 'en' => 'France'],
    'IT' => ['flag' => '🇮🇹', 'uk' => 'Італія', 'en' => 'Italy'],
    'ES' => ['flag' => '🇪🇸', 'uk' => 'Іспанія', 'en' => 'Spain'],
    'PT' => ['flag' => '🇵🇹', 'uk' => 'Португалія', 'en' => 'Portugal'],
    'NL' => ['flag' => '🇳🇱', 'uk' => 'Нідерланди', 'en' => 'Netherlands'],
    'BE' => ['flag' => '🇧🇪', 'uk' => 'Бельгія', 'en' => 'Belgium'],
    'CZ' => ['flag' => '🇨🇿', 'uk' => 'Чехія', 'en' => 'Czechia'],
    'SK' => ['flag' => '🇸🇰', 'uk' => 'Словаччина', 'en' => 'Slovakia'],
    'HU' => ['flag' => '🇭🇺', 'uk' => 'Угорщина', 'en' => 'Hungary'],
    'RO' => ['flag' => '🇷🇴', 'uk' => 'Румунія', 'en' => 'Romania'],
    'MD' => ['flag' => '🇲🇩', 'uk' => 'Молдова', 'en' => 'Moldova'],
    'LT' => ['flag' => '🇱🇹', 'uk' => 'Литва', 'en' => 'Lithuania'],
    'LV' => ['flag' => '🇱🇻', 'uk' => 'Латвія', 'en' => 'Latvia'],
    'EE' => ['flag' => '🇪🇪', 'uk' => 'Естонія', 'en' => 'Estonia'],
    'SE' => ['flag' => '🇸🇪', 'uk' => 'Швеція', 'en' => 'Sweden'],
    'NO' => ['flag' => '🇳🇴', 'uk' => 'Норвегія', 'en' => 'Norway'],
    'FI' => ['flag' => '🇫🇮', 'uk' => 'Фінляндія', 'en' => 'Finland'],
    'DK' => ['flag' => '🇩🇰', 'uk' => 'Данія', 'en' => 'Denmark'],
    'GB' => ['flag' => '🇬🇧', 'uk' => 'Велика Британія', 'en' => 'United Kingdom'],
    'IE' => ['flag' => '🇮🇪', 'uk' => 'Ірландія', 'en' => 'Ireland'],
    'US' => ['flag' => '🇺🇸', 'uk' => 'США', 'en' => 'United States'],
    'CA' => ['flag' => '🇨🇦', 'uk' => 'Канада', 'en' => 'Canada'],
    'MX' => ['flag' => '🇲🇽', 'uk' => 'Мексика', 'en' => 'Mexico'],
    'BR' => ['flag' => '🇧🇷', 'uk' => 'Бразилія', 'en' => 'Brazil'],
    'AR' => ['flag' => '🇦🇷', 'uk' => 'Аргентина', 'en' => 'Argentina'],
    'TR' => ['flag' => '🇹🇷', 'uk' => 'Туреччина', 'en' => 'Turkey'],
    'IL' => ['flag' => '🇮🇱', 'uk' => 'Ізраїль', 'en' => 'Israel'],
    'AE' => ['flag' => '🇦🇪', 'uk' => 'ОАЕ', 'en' => 'United Arab Emirates'],
    'IN' => ['flag' => '🇮🇳', 'uk' => 'Індія', 'en' => 'India'],
    'CN' => ['flag' => '🇨🇳', 'uk' => 'Китай', 'en' => 'China'],
    'JP' => ['flag' => '🇯🇵', 'uk' => 'Японія', 'en' => 'Japan'],
    'KR' => ['flag' => '🇰🇷', 'uk' => 'Південна Корея', 'en' => 'South Korea'],
    'AU' => ['flag' => '🇦🇺', 'uk' => 'Австралія', 'en' => 'Australia'],
    'NZ' => ['flag' => '🇳🇿', 'uk' => 'Нова Зеландія', 'en' => 'New Zealand'],
];
